// Generated by wxt
export {}
declare global {
  const AnimationAssets: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/utils/animationAssets')['AnimationAssets']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const DurationPicker: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/components/DurationPicker')['default']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const SplitButton: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/components/SplitButton')['default']
  const Timer: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/components/Timer')['default']
  const TimerArt: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/components/TimerArtWeb')['TimerArt']
  const TimerArtVariants: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/components/TimerArtWeb')['TimerArtVariants']
  const TimerService: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/components/timerService')['TimerService']
  const browser: typeof import('wxt/browser/chrome')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getAnimationAsset: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/utils/animationAssets')['getAnimationAsset']
  const injectScript: typeof import('wxt/client')['injectScript']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useTimer: typeof import('/Users/acap/browserbuddy/submissions/pixfocus-ext/components/useTimer')['useTimer']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { TimerService } from '/Users/acap/browserbuddy/submissions/pixfocus-ext/components/timerService'
  import('/Users/acap/browserbuddy/submissions/pixfocus-ext/components/timerService')
}
